safe: true
lsi: false
source: .
destination: ./_site
markdown: rdiscount
pygments: true

name: "limed's blog"
description: "Blog documenting random notes of limed"
url: "http://sudoers.org"
author: "Ed Lim"
twitter: limed
github: limed
